<?php
/*
 * view/home.php
 * --------------
 * Main application interface
 */
	if (!defined('GOOGLE_APIKEY')) return;
	if (!isset($currentSessionData)) $currentSessionData = null;
	
	$currentUserNickName = (!isset($currentSessionData['userNickName']) ?
			'Anonymous' : $currentSessionData['userNickName']);
?>
<!DOCTYPE html>

<html lang="id">
	<head>
		<meta charset="UTF-8" />
		<meta name="description" content=""/>
		<meta name="keywords" content=""/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title><?php
			if (isset($pageTitle)) echo htmlspecialchars($pageTitle);
			else echo "Untitled";
		?> | AngkotTracer</title>
		<link rel="icon" href="<?php echo $baseUrl.('/assets/favicon.ico'); ?>" type="image/x-icon" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/bootstrap.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/font-awesome.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/toastr.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/global.css?ver='.APPVER); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/select2.min.css'); ?>" type="text/css" media="screen" />
<style>
#site_floatpanel {
  position: absolute;
  top: 42px;
  right: 10px;
  z-index: 5;
  background-color: #fff;
  padding: 7px;
  border: 1px solid #999;
  font-family: 'Roboto','sans-serif';
  line-height: 30px;
  min-height:32px;
}

#site_floatpanel_extension {
  position: absolute;
  top: 42px;
  right: 180px;
  z-index: 5;
  background-color: #fff;
  padding: 7px;
  border: 1px solid #999;
  font-family: 'Roboto','sans-serif';
  line-height: 30px;
  min-height:32px;
}

#site_floatpanel .fpanel_item {display:none;}

.searchresult_step {display:none;}

/* ----------- CONTEXT MENU -------------- */
.context-menu {
	width: 200px;
	position: absolute;
	background: white;
	color: #666;
	font-weight: bold;
	border: 1px solid #999;
	font-family: sans-serif;
	font-size: 12px;
	box-shadow: 1px 3px 3px rgba(0, 0, 0, .3);
	margin-top: -15px;
	margin-left: 10px;
	cursor: pointer;
}
.context-menu hr {
	margin-top: 5px;
	margin-bottom: 5px;
}
.context-menu .arrow {
	position: absolute;
	left: -5px;
	top: 8px;
	width: 0;
	height: 0;
	border-top: 5px solid transparent;
	border-bottom: 5px solid transparent;
	border-right: 5px solid #fff;
}
.context-menu .arrowborder {
	position: absolute;
	left: -7px;
	top: 6px;
	width: 0;
	height: 0;
	border-top: 7px solid transparent;
	border-bottom: 7px solid transparent;
	border-right: 7px solid #999;
}

.context-menu .menu-item {
	display: block;
	padding: 5px;
	text-decoration: none;
}
.context-menu .menu-item:hover {
	background: #eee;
	text-decoration: none;
}

#ctxmenu-0-delete, #ctxmenu-0-delete:hover {
	color: #a94442;
}

</style>
		<script src="<?php echo $baseUrl.('/assets/js/jquery.min.js'); ?>"></script>
		
	</head>
	<body>
<?php if ($currentSessionData !== null) { //------- Show entire body if user has been logged in -------- ?>
<div id="site_navbar" class="blocking_elmt">
	<strong>Angkot Semarang</strong> Route Editor <?php echo APPVER; ?>
	<div class="pull-right">
		<i class="fa fa-user"></i> Logged in As <strong><a href="#showmenu" onclick="return show_usermenu();">
			<?php echo htmlspecialchars($currentUserNickName); ?> <i class="fa fa-caret-down"></i></a></strong>
	</div>
</div>
<div id="site_mainwrapper" style="padding-top:32px;" class="blocking_elmt">
	<div id="site_leftpanel">
		<!-- <h2>Angkot Tracer</h2> -->
		<!-- <small>Ayo naik angkutan umum!</small> -->
		
		<!-- <div style="height:64px;background-color:#eee;margin-bottom:10px;"></div> -->
		<form class="horizontal-form" action="#goto" id="site_gotoplace" onsubmit="return editor_gotoplace_submit();">
			<div class="form-group">
				<label for="txt_gotoplace">Ke lokasi:</label>
				<input type="text" class="form-control input-sm" name="txt_gotoplace"
					id="txt_gotoplace" placeholder="Cari daerah" />
			</div>
		</form>
		<hr>
		<ul class="nav nav-pills nav-stacked" id="homemenu">
			<li id="homemenu_grapheditor"><a href="#" onclick="return reset_gui();">
				<i class="fa fa-share-alt fa-fw"></i> Graph Editor</a></li>
			<li id="homemenu_routeeditor"><a href="#" onclick="return init_routeeditor();">
				<i class="fa fa-bus fa-fw"></i> Public Route Editor</a></li>
			<!-- <li id="homemenu_routedebug"><a href="#" onclick="return init_routedebug();">
				<i class="fa fa-bolt fa-fw"></i> Route Debugger</a></li> -->
		</ul>
		<hr>
	<div id="site_actionpanel_container">
		<!-- 
		<div id="site_panel_nodelist" style="display:none;">
			<form class="horizontal-form" id="site_nodeselector">
				<label>Pilih node:</label>
				<select name="nodeid" class="form-control">
					<option value="0">- Pilih -</option>
				</select>
			</form>
			<button onclick="return download_json();" class="btn btn-default btn-block">Get Data</button>
		</div> -->
		<div id="site_panel_nodeinsert" class="site_defaultpanel">
			<button onclick="return new_node();" class="btn btn-default btn-block">
				<i class="fa fa-plus"></i> Insert New Node</button>
		</div>
		<div id="site_panel_placenode" class="site_actionpanel">
			<p>Klik pada map untuk menaruh di mana node akan ditempatkan.</p>
			<button onclick="return cancel_picker();" class="btn btn-danger btn-block">Batal</button>
		</div>
		<div id="site_panel_selectnode" class="site_actionpanel">
			<p>Pilih salah satu node dengan klik..</p>
			<button onclick="return cancel_picker();" class="btn btn-danger btn-block">Batal</button>
		</div>
		<div id="site_panel_movenode" class="site_actionpanel">
			<p>Drag marker node ke titik yang diinginkan, lalu klik Save.</p>
			<button onclick="return node_move_commit();" class="btn btn-primary btn-block">
				<i class="fa fa-floppy-o"></i> Save</button>
			<button onclick="return reset_gui();" class="btn btn-danger btn-block">
				<i class="fa fa-times"></i> Batal</button>
		</div>
		<div id="site_panel_selectedge" class="site_actionpanel">
			<p>Ubah polyline pada peta, lalu klik save untuk menyimpan.</p>
			<form action="#" method="POST" onsubmit="return edge_save();">
				<div class="form-group">
					<label for="edge_name">Nama Busur/Jalan</label>
					<input type="text" class="form-control input-sm" name="edge_nameid"
						id="edge_name" placeholder="Nama Edge" />
				</div>
				<div class="checkbox">
			        <label>
			          <input type="checkbox" id="edge_isreversible" name="edge_isreversible"
			          	onchange="edge_isreversible_onupdate(this);"/> Reversible
			        </label>
				</div>
				<button type="submit" class="btn btn-primary btn-block">
					<i class="fa fa-floppy-o"></i> Save</button>
				<button onclick="return reset_gui();" class="btn btn-danger btn-block" >
					<i class="fa fa-times"></i> Batal</button>
			</form>
				
			
		</div>
		
		<div id="site_panel_routeeditor_home" class="site_actionpanel">
			<button onclick="return new_route();" class="btn btn-default btn-block">
				<i class="fa fa-plus"></i> Create New Route...</button>
			<button onclick="return select_route();" class="btn btn-default btn-block">
				<i class="fa fa-folder-open"></i> Select Route...</button>
		</div>
		<div id="site_panel_routeeditor_draw" class="site_actionpanel">
			<form action="#" method="POST" onsubmit="return route_save(this);">
				<div class="form-group">
					<label for="txt_route_name">Nama Trayek</label>
					<input type="text" class="form-control input-sm" name="txt_route_name"
						id="txt_route_name" placeholder="Nama Trayek." />
					<p class="help-block">Nama trayek. Misal: Johar-Tlogosari</p>
				</div>
				<div class="row">
					<div class="form-group col-xs-6">
						<label for="txt_route_code">Kode</label>
						<input type="text" class="form-control input-sm" name="txt_route_code"
							id="txt_route_code" placeholder="Kode armada" />
					</div>
					<div class="form-group col-xs-6">
						<label for="txt_route_type">Jenis</label>
						<select name="txt_route_type" id="txt_route_type"
								class="form-control" required>
							<option value="">- Pilih -</option>
							<option value="1">Angkota</option>
							<option value="2">BRT</option>
						</select>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-xs-6">
						<label for="txt_route_direction">Arah Trayek</label>
						<select name="txt_route_direction" id="txt_route_direction"
								class="form-control" required>
							<option value="">- Pilih -</option>
							<option value="a">Berangkat</option>
							<option value="b">Pulang</option>
						</select>
					</div>
					<div class="form-group col-xs-6">
						<label for="txt_route_status">Status</label>
						<select name="txt_route_status" id="txt_route_status"
								class="form-control" required>
							<option value="yes">Aktif</option>
							<option value="no">Non-aktif</option>
						</select>
					</div>
				</div>
				
				<button type="submit" class="btn btn-primary btn-block">
					<i class="fa fa-floppy-o"></i> Save</button>
				<button onclick="return routeeditor_draw_cancel();" class="btn btn-danger btn-block" >
					<i class="fa fa-times"></i> Batal</button>
				<input type="hidden" name="verb" value="route.save" />
			</form>
		</div>
		<div id="site_panel_nodeselected" class="site_actionpanel">
			<button onclick="return new_node();" class="btn btn-default btn-block">
				<i class="fa fa-plus"></i> Connect to New Node...</button>
			
			<!-- <h4>List Simpul</h4>
			<div class="table-responsive">
				<table class="table table-striped table-condensed table-hover table-bordered"
						 id="table_edge">
					<thead>
						<tr>
							<th>Node</th>
							<th>Distance</th>
							<th title="Reversible?">R</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
						
					</tbody>
				</table>
			</div> -->
			
			<button class="btn btn-primary btn-block" onclick="new_edge();">
				<i class="fa fa-crosshairs"></i> Connect to Existing Node...</button>
			<!-- <button class="btn btn-default btn-block" onclick="get_direction();">
				<i class="fa fa-car"></i> Get Direction...</button> -->
			
			<form action="#" id="site_nodeform" style="display:none;">
				<label for="site_nodedest_txt">Destination Node</label>
				<select name="id_node" class="form-control"></select>
				<label for="site_nodedist_txt">Distance</label>
				<input type="text" name="node_dist" value="" id="site_nodedist_txt" class="form-control"/>
				<input type="checkbox" name="node_reversible" id="site_reversible_chk"/>
				<label for="site_reversible_chk">Reversible</label>
				
			</form>
		</div><!-- End panel -->
		
		<div id="site_panel_routedebug" class="site_actionpanel">
			<pre id="routedebug_logpanel" style="max-height: 350px;"></pre>
		</div>
		
	</div><!-- end action panel container -->
	</div>
	<div id="site_googlemaps"></div>
	
	<div id="site_floatpanel">
		<div id="fpanel_home" style="width: 150px;">
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="new_node(); return false;">
				<i class="fa fa-plus"></i> Tambah Node</a>
		</div>
		<div id="fpanel_drawroute" class="fpanel_item" style="width: 300px;">
			<h5>Route</h5>
			<a href="#" class="btn btn-danger btn-sm btn-block" onclick="return routeeditor_draw_delete();">
				<i class="fa fa-trash"></i> Delete Route</a>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return routeeditor_draw_reset();">
				<i class="fa fa-times"></i> Clear and Reset Route</a>
			<div class="table-responsive" style="overflow-y: scroll; height: 400px; padding: 5px; border:solid 1px #F5F5F5;"
					id="container_tablerouteedge">
				<table class="table table-striped table-condensed table-hover table-bordered"
						 id="table_routeedge">
					<thead>
						<tr>
							<th>Node</th>
							<th>Name</th>
						</tr>
					</thead>
					<tbody>
						
					</tbody>
				</table>
			</div>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return routeeditor_draw_backward();">
				<i class="fa fa-chevron-left"></i> Back</a>
		</div>
		<div id="fpanel_edgeedit" class="fpanel_item" style="width: 150px;">
			<div style="text-align: center; font-size:1.1em;"><b>Edge options:</b></div>
			<b>Distance</b>: <span id="edgeedit_distance">-</span> km.
			<hr />
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return edge_showprops();">
				<i class="fa fa-pencil"></i> Properties...</a>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return edge_reset();">
				<i class="fa fa-undo"></i> Reset</a>
			<div style="text-align:center;">
				<div class="btn-group" style="margin-top:5px;">
					<button type="button" class="btn btn-default btn-sm dropdown-toggle"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-road"></i> Get Direction <span class="caret"></span></button>
					<ul class="dropdown-menu" id="requestdirection_opts" style="min-width: 120px;">
						<li><a href="#reqdir" onclick="return edge_getdir();">From A to B</a></li>
						<li><a href="#reqdirrev" onclick="return edge_getdir(-1);">From B to A</a></li>
					</ul>
				</div>
			</div>
			<hr />
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return edge_interpolate();">
				<i class="fa fa-cogs"></i> Interpolate</a>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return edge_reverse_current();"
				id="fpanel_edge_btnreverse"><i class="fa fa-exchange"></i> Reverse</a>
			<hr />
			<a href="#" class="btn btn-danger btn-sm btn-block" onclick="return edge_delete();"
				id="fpanel_edge_btndelete"><i class="fa fa-trash"></i> Delete</a>
		</div>
		<div id="fpanel_nodeedit" class="fpanel_item" style="width: 150px;">
			<b>Node options:</b><hr />
			<a href="#" class="btn btn-link btn-sm btn-block" onclick="return node_edit_recenter();">
				<i class="fa fa-crosshairs"></i> Re-Center</a>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return node_showprops();">
				<i class="fa fa-pencil"></i> Properties...</a>
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return node_move();"><i class="fa fa-arrows"></i> Move</a>
			<a href="#" class="btn btn-danger btn-sm btn-block" onclick="return node_delete();"><i class="fa fa-trash"></i> Delete</a>
		</div>
		<div id="fpanel_nodemove" class="fpanel_item" style="width: 150px;">
			<b>Node options:</b><hr />
			<a href="#" class="btn btn-default btn-sm btn-block" onclick="return node_move_reset();"><i class="fa fa-undo"></i> Reset</a>
			<a href="#" class="btn btn-danger btn-sm btn-block" onclick="return node_delete();"><i class="fa fa-trash"></i> Delete</a>
		</div>
		<div id="fpanel_searchresult" class="fpanel_item" style="width: 450px;">
			<div style="background-color:#eee;padding:5px;">
				<a href="#" onclick="return nav_directionstep(0);"> First</a> |
				<a href="#" onclick="return nav_directionstep('-');"> Prev</a>
				<div class="pull-right">
					<a href="#" onclick="return nav_directionstep('+');"> Next</a> |
					<a href="#" onclick="return nav_directionstep('max');"> Last</a>
				</div>
			</div>
			<div id="searchresult_step_container" style="min-height: 400px;overflow-y:scroll;">
				
			</div>
			<div id="searchresult_step_result" style="display:none;">
				<div class="list-group">
					<a href="#" class="list-group-item">
						<div class="media">
						  <div class="media-left">
						  	<!-- <i class="fa fa-bus fa-2x"></i> -->
						  	<img src="<?php echo _base_url('/assets/images/angkot/semarang-c9.png'); ?>" style="width:64px;"/>
						  </div>
						  <div class="media-body">
						    Test<br />
						    Mlampah
						  </div>
						</div>
					</a>
					<a href="#" class="list-group-item">
						<div class="media">
						  <div class="media-left">
						  	<i class="fa fa-male fa-2x"></i>
						  </div>
						  <div class="media-body">
						    Test<br />
						    Mlampah
						  </div>
						</div>
					</a>
				</div>
			</div><!-- End step box -->
			
		</div>
	</div>
	<div id="site_floatpanel_extension">
		<div id="fpanel_nodeopts" class="fpanelext_item" style="width: 200px; display:none;">
			<form action="#" onsubmit="return node_submit_nodeprops();" id="form_floatpanel_node">
				<b>Node options:</b><hr />
				<?php echo @$nodeFormContent; ?>
				<hr />
				<button class="btn btn-primary btn-sm btn-block" type="submit">
					<i class="fa fa-floppy-o"></i> Save</button>
				<button class="btn btn-danger btn-sm btn-block" type="button" onclick="hide_fpanel_ext();">
					<i class="fa fa-times"></i> Cancel</button>
			</form>
		</div>
		<div id="fpanel_edgeopts" class="fpanelext_item" style="width: 200px; display:none;">
			
		</div>
	</div>
</div>
<?php } //--------- End if logged in ------------- ?>
<script>
var SESSIONDATA = <?php echo json_encode($currentSessionData); ?>;
var MARKERBASE = "<?php echo $baseUrl.('/assets/images/marker/'); ?>";
var scripts = <?php echo json_encode(array(
	'markerclusterer' => $baseUrl.('/assets/js/components/marker-clusterer.js?v='.APPVER),
	'ctxmenu' => $baseUrl.('/assets/js/components/gmap-contextmenu.js?v='.APPVER),
	'vertex-mgmt' => $baseUrl.('/assets/js/main/vertex.js?v='.APPVER),
	'edge-mgmt' => $baseUrl.('/assets/js/main/edge.js?v='.APPVER),
	'route-mgmt' => $baseUrl.('/assets/js/main/route.js?v='.APPVER)
)); ?>;
</script>
<script src="<?php echo $baseUrl.('/assets/js/home.js?v='.APPVER); ?>"></script>
<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=<?php echo GOOGLE_APIKEY; ?>&libraries=places,geometry&callback=init_map"></script>
	
<!-- modal dialogs -->
		<div id='site_overlay_modal'>
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<div id='site_ov_box_modal'>
							<div id="site_modal_loader">
								<img src='<?php echo $baseUrl.('/assets/images/loader.gif'); ?>' alt='Loading...' /> Memuat...
							</div>
							<div id="site_modal_content">							
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div id='site_overlay_process'>
			<div id='site_ov_box_process'>
				<div id='site_ov_msg_process'>Sedang memproses... Mohon tunggu...</div>
				<img src='<?php echo $baseUrl.('/assets/images/loader.gif'); ?>' alt='Loading...'
					id="site_ov_icon_process"/>
			</div>
		</div>
		
		<div id='site_overlay_message'>
			<div id='site_ov_box_message'>
				<div id='site_ov_msg_message'></div>
			</div>
		</div>
		
		<div style="display:none;">
			<div id="site_htmlcontent_loginalert">
				Please login to access this page.
				<hr />
				<div style="text-align:center;">
					<a href="<?php echo $baseUrl.('/auth/login?ref=editor'); ?>" class="btn btn-primary">
						<i class='fa fa-lock'></i> Login Page
					</a>
				</div>
			</div>
			<div id="site_htmlcontent_expiredsession">
				Your session is invalid or has been expired. Please re-login to continue.
				<hr />
				<div style="text-align:center;">
					<a href="<?php echo $baseUrl.('/auth/login?ref=editor'); ?>" class="btn btn-primary">
						<i class='fa fa-lock'></i> Login Page
					</a>
				</div>
			</div>
		</div>
		
		<script>
		var AJAX_REQ_URL = "<?php echo $baseUrl; ?>";
		var URL_DATA_AJAX = "<?php echo $baseUrl.('/app'); ?>";
		var URL_MODAL = "<?php echo $baseUrl.('/modal/get_modal'); ?>";
		var URL_ALGORITHM_AJAX = "<?php echo $baseUrl.('/algorithm'); ?>";
		</script>
		<script src="<?php echo $baseUrl.('/assets/js/bootstrap.min.js'); ?>"></script>
		<script src="<?php echo $baseUrl.('/assets/js/toastr.min.js'); ?>"></script>
		<script src="<?php echo $baseUrl.('/assets/js/select2.min.js?v='.APPVER); ?>"></script>
		<script src="<?php echo $baseUrl.('/assets/js/global.js?v='.APPVER); ?>"></script>
		<textarea style="display:none;"><?php echo "</body></html>"; ?></textarea>
	</body>
</html>