<?php
/*
 * templates/index.phtml
 * ----------------------
 * Main public application interface
 */
	if (!defined('GOOGLE_APIKEY')) return;
	
?>
<!DOCTYPE html>

<html lang="id">
	<head>
		<meta charset="UTF-8" />
		<meta name="description" content=""/>
		<meta name="keywords" content=""/>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<title><?php
			if (isset($data['pageTitle'])) echo htmlspecialchars($data['pageTitle']);
			else echo "Untitled";
		?> | AngkotTracer</title>
		<link rel="icon" href="<?php echo $baseUrl.('/assets/favicon.ico'); ?>" type="image/x-icon" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/bootstrap.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/font-awesome.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/toastr.min.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/global.css'); ?>" type="text/css" media="screen" />
		<link rel="stylesheet" href="<?php echo $baseUrl.('/assets/css/select2.min.css'); ?>" type="text/css" media="screen" />
		
		<script src="<?php echo $baseUrl.('/assets/js/jquery.min.js'); ?>"></script>
<style>
#site_floatpanel {
  position: absolute;
  top: 10px;
  left: 10px;
  z-index: 5;
  background-color: #fff;
  padding: 7px;
  border: 1px solid #999;
  font-family: 'Roboto','sans-serif';
  min-height:32px;
}
</style>
	</head>
	<body>

		<div id="site_mainwrapper" style="min-width:800px;">
			<div id="site_googlemaps" style="margin-left:330px;"></div>
			
			<div id="site_floatpanel">
				<div style="width: 300px;">
					<h2>Angkot Semarang</h2>
					<hr />
					<div class="site_defaultpanel">
						<form class="horizontal-form" action="#submit" id="site_mainform" onsubmit="return mainform_submit();">
							
							<fieldset>
								<legend style="font-size: 16px;margin-bottom:10px;">Starting Point</legend>
								<div><a href="#" style="color:#999;" id="site_start_geo">Unselected</a></div>
								<a href="#" onclick="return pick_start_point();"><i class="fa fa-crosshairs"></i> Select location</a>
								<div class="form-group">
									<input type="text" class="form-control input-sm" name="txt_node_start"
										id="txt_node_start" placeholder="Tempat berangkat." />
								</div>
							</fieldset>
							<fieldset>
								<legend style="font-size: 16px;margin-bottom:10px;">Destination</legend>
								<div class="form-group">
									<div><a href="#" style="color:#999;" id="site_dest_geo">Unselected</a></div>
									<a href="#" onclick="return pick_dest_point();"><i class="fa fa-crosshairs"></i> Select location</a>
									<input type="text" class="form-control input-sm" name="txt_node_dest"
										id="txt_node_dest" placeholder="Tempat tujuan." />
								</div>
								
							</fieldset>
							<fieldset>
								<legend style="font-size: 16px;margin-bottom:10px;">Preferensi</legend>
								<div class="form-group">
	<div class="checkbox">
		<label><input type="checkbox" checked="checked" name="angkot" value="1" id="chk_angkot" />
			Angkutan Kota (Angkot)</label>
	</div>
	<div class="checkbox">
		<label><input type="checkbox" checked="checked" name="brt" value="1" id="chk_brt" />
			Bus Rapid Transit (BRT)</label>
	</div>
								</div>
								
							</fieldset>
							<button type="submit" class="btn btn-primary btn-block" disabled id="btn_beginsearch">
								<i class="fa fa-search"></i> Search Route</button>
						</form>
					</div>
					<div id="site_panel_placenode" class="fpanel_item" style="display:none;">
						<p class="message">Klik pada map untuk menaruh di mana node akan ditempatkan.</p>
						<button onclick="return cancel_picker();" class="btn btn-danger btn-block">Batal</button>
					</div>
					<div id="site_panel_searchresult" class="fpanel_item" style="display:none;">
						<a href="#" onclick="return reset_gui();" class="btn btn-link btn-block"><i class="fa fa-remove"></i> Reset</a>
	<form class="horizontal-form" action="#submit">
		<select name="combo_routeway_list" class="form-control" id="combo_routeway_list"
			onchange="searchresult_comboupdated();">
			
		</select>
	</form>
	<hr />
					<div id="listgroup_steps" style="height: 300px;overflow-y:scroll;">
						<div class="list-group">
							<a href="#" class="list-group-item">
								<div class="media">
								  <div class="media-left">
								  	<!-- <i class="fa fa-bus fa-2x"></i> -->
								  	<img src="<?php echo _base_url('/assets/images/angkot/semarang-c9.png'); ?>" style="width:64px;"/>
								  </div>
								  <div class="media-body">
								    Test<br />
								    Mlampah
								  </div>
								</div>
							</a>
							<a href="#" class="list-group-item">
								<div class="media">
								  <div class="media-left">
								  	<i class="fa fa-male fa-2x"></i>
								  </div>
								  <div class="media-body">
								    Test<br />
								    Mlampah
								  </div>
								</div>
							</a>
						</div>
					</div><!-- End listgroup steps -->
					</div>
				</div>
			</div>
		</div>
		
<div id='site_overlay_process'>
	<div id='site_ov_box_process'>
		<div id='site_ov_msg_process'>Sedang memproses... Mohon tunggu...</div>
		<img src='<?php echo $baseUrl.('/assets/images/loader.gif'); ?>' alt='Loading...' />
	</div>
</div>

<script>
var MARKERBASE = "<?php echo $baseUrl.('/assets/images/marker/'); ?>";
var AJAX_REQ_URL = "<?php echo $baseUrl; ?>";
var URL_DATA_AJAX = "<?php echo $baseUrl.('/app'); ?>";
var URL_MODAL = "<?php echo $baseUrl.('/modal/get_modal'); ?>";
var URL_ALGORITHM_AJAX = "<?php echo $baseUrl.('/algorithm'); ?>";
</script>
<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=<?php echo GOOGLE_APIKEY; ?>&libraries=places,geometry&callback=init_map"></script>
<script src="<?php echo $baseUrl.('/assets/js/bootstrap.min.js'); ?>"></script>
<script src="<?php echo $baseUrl.('/assets/js/toastr.min.js'); ?>"></script>
<script src="<?php echo $baseUrl.('/assets/js/select2.min.js?v='.APPVER); ?>"></script>
<script src="<?php echo $baseUrl.('/assets/js/global.js?v='.APPVER); ?>"></script>
<script src="<?php echo $baseUrl.('/assets/js/frontpage.js?v='.APPVER); ?>"></script>

	</body>
</html>